-- Semilla de permisos y roles de fábrica. GENERADA por
-- packages/core/scripts/permisos-sql.ts desde packages/core/src/permisos.ts (ACC-1).
-- No se edita a mano: se cambia el catálogo y se vuelve a generar
-- con `pnpm --filter @mc/core permisos:sql`. Re-ejecutable.

-- 45 permisos.
INSERT INTO permission (key, module, label_es, sensitivity) VALUES
  ('resumen.panel.ver', 'resumen', 'Ver el resumen', 'normal'),
  ('resumen.metricas.importar', 'resumen', 'Importar métricas por CSV', 'normal'),
  ('ventas.senal.ver', 'ventas', 'Ver el radar de señales', 'normal'),
  ('ventas.senal.registrar', 'ventas', 'Anotar, aceptar y descartar señales', 'normal'),
  ('ventas.senal.importar', 'ventas', 'Cargar una lista de marcas por CSV', 'normal'),
  ('ventas.empresa.ver', 'ventas', 'Ver empresas y contactos', 'normal'),
  ('ventas.empresa.crear', 'ventas', 'Crear empresas', 'normal'),
  ('ventas.empresa.editar', 'ventas', 'Editar empresas y sus contactos', 'normal'),
  ('ventas.negocio.ver', 'ventas', 'Ver el pipeline de negocios', 'normal'),
  ('ventas.negocio.crear', 'ventas', 'Crear negocios', 'normal'),
  ('ventas.negocio.editar', 'ventas', 'Mover negocios de etapa', 'normal'),
  ('cotizar.tarifario.ver', 'cotizar', 'Ver el tarifario', 'normal'),
  ('cotizar.tarifario.editar', 'cotizar', 'Guardar el tarifario', 'normal'),
  ('cotizar.mediakit.ver', 'cotizar', 'Ver los media kits', 'normal'),
  ('cotizar.mediakit.generar', 'cotizar', 'Generar un media kit', 'normal'),
  ('cotizar.mediakit.editar', 'cotizar', 'Publicar, despublicar y desbloquear media kits', 'normal'),
  ('cotizar.cotizacion.ver', 'cotizar', 'Ver las cotizaciones', 'normal'),
  ('cotizar.cotizacion.crear', 'cotizar', 'Crear cotizaciones', 'normal'),
  ('cotizar.cotizacion.editar', 'cotizar', 'Editar y borrar borradores de cotización', 'normal'),
  ('cotizar.cotizacion.enviar', 'cotizar', 'Enviar cotizaciones y registrar la respuesta de la marca', 'normal'),
  ('campanas.campana.ver', 'campanas', 'Ver las campañas', 'normal'),
  ('campanas.campana.crear', 'campanas', 'Crear campañas', 'normal'),
  ('campanas.campana.editar', 'campanas', 'Editar campañas y cambiar su estado', 'normal'),
  ('campanas.post.asociar', 'campanas', 'Asociar posts y marcar entregables', 'normal'),
  ('campanas.aporte.registrar', 'campanas', 'Registrar lo que aporta la marca', 'normal'),
  ('campanas.resultado.calcular', 'campanas', 'Recalcular el resultado de una campaña', 'normal'),
  ('campanas.reporte.generar', 'campanas', 'Generar el reporte a la marca', 'normal'),
  ('campanas.reporte.enviar', 'campanas', 'Enviar el reporte a la marca', 'normal'),
  ('finanzas.factura.ver', 'finanzas', 'Ver las facturas', 'sensible'),
  ('finanzas.factura.crear', 'finanzas', 'Crear facturas', 'sensible'),
  ('finanzas.factura.editar', 'finanzas', 'Marcar facturas como enviadas o anularlas', 'sensible'),
  ('finanzas.pago.registrar', 'finanzas', 'Registrar pagos', 'sensible'),
  ('finanzas.cobro.ver', 'finanzas', 'Ver el estado de cobro de las campañas', 'sensible'),
  ('finanzas.gasto.ver', 'finanzas', 'Ver los gastos', 'sensible'),
  ('finanzas.gasto.registrar', 'finanzas', 'Registrar gastos', 'sensible'),
  ('finanzas.flujo.ver', 'finanzas', 'Ver el flujo de caja y la reserva de impuestos', 'sensible'),
  ('finanzas.ajustes.configurar', 'finanzas', 'Configurar los parámetros financieros', 'sensible'),
  ('conexiones.cuenta.ver', 'conexiones', 'Ver el estado de las cuentas conectadas', 'normal'),
  ('conexiones.cuenta.conectar', 'conexiones', 'Conectar cuentas y pedir una lectura nueva', 'sensible'),
  ('conexiones.cuenta.desconectar', 'conexiones', 'Quitar cuentas conectadas', 'sensible'),
  ('equipo.miembro.ver', 'equipo', 'Ver quién está en el espacio', 'sensible'),
  ('equipo.miembro.invitar', 'equipo', 'Invitar personas al espacio', 'sensible'),
  ('equipo.miembro.revocar', 'equipo', 'Quitar personas del espacio', 'sensible'),
  ('equipo.rol.editar', 'equipo', 'Cambiar el rol de una persona', 'sensible'),
  ('equipo.workspace.configurar', 'equipo', 'Configurar el espacio y cerrar la cuenta', 'sensible')
ON CONFLICT (key) DO NOTHING;

-- 10 roles de sistema (workspace_id IS NULL).
INSERT INTO role (workspace_id, key, workspace_kind, label_es, description_es, is_system) VALUES
  (NULL, 'owner', 'creator', 'Dueño', 'El creador. Todo, incluido el equipo y la cuenta.', true),
  (NULL, 'manager', 'creator', 'Mánager', 'Su agente, quien habla con las marcas. Ventas, Cotizar y Campañas completas, el estado de cobro de las campañas, y ve el resto. No conecta cuentas ni ve el flujo de caja.', true),
  (NULL, 'editor', 'creator', 'Editor', 'Community manager o editor de video. Ve las campañas y marca sus entregables.', true),
  (NULL, 'finance', 'creator', 'Contador', 'Contador externo. Todo Finanzas; las campañas las ve por sus facturas.', true),
  (NULL, 'viewer', 'creator', 'Solo lectura', 'Quien mira y no toca. Sin Finanzas ni Equipo.', true),
  (NULL, 'owner', 'agency', 'Dueño', 'Toda la agencia, incluidas la facturación de la cuenta y su cierre.', true),
  (NULL, 'admin', 'agency', 'Administrador', 'Personas, roles y marcas de toda la agencia. No configura ni cierra la cuenta.', true),
  (NULL, 'manager', 'agency', 'Ejecutivo de cuenta', 'Ventas, Cotizar y Campañas de las marcas o creadores que tiene asignados.', true),
  (NULL, 'finance', 'agency', 'Contador', 'Finanzas de la agencia.', true),
  (NULL, 'viewer', 'agency', 'Solo lectura', 'Ver lo que se le asigne. Sin Finanzas ni Equipo.', true)
ON CONFLICT (key, workspace_kind) WHERE workspace_id IS NULL DO NOTHING;

-- 230 filas de la matriz. El role_id se resuelve por (key, workspace_kind) porque es gen_random_uuid().
INSERT INTO role_permission (role_id, permission_key)
SELECT r.id, m.permission_key
FROM (VALUES
  ('owner', 'creator', 'resumen.panel.ver'),
  ('owner', 'creator', 'resumen.metricas.importar'),
  ('owner', 'creator', 'ventas.senal.ver'),
  ('owner', 'creator', 'ventas.senal.registrar'),
  ('owner', 'creator', 'ventas.senal.importar'),
  ('owner', 'creator', 'ventas.empresa.ver'),
  ('owner', 'creator', 'ventas.empresa.crear'),
  ('owner', 'creator', 'ventas.empresa.editar'),
  ('owner', 'creator', 'ventas.negocio.ver'),
  ('owner', 'creator', 'ventas.negocio.crear'),
  ('owner', 'creator', 'ventas.negocio.editar'),
  ('owner', 'creator', 'cotizar.tarifario.ver'),
  ('owner', 'creator', 'cotizar.tarifario.editar'),
  ('owner', 'creator', 'cotizar.mediakit.ver'),
  ('owner', 'creator', 'cotizar.mediakit.generar'),
  ('owner', 'creator', 'cotizar.mediakit.editar'),
  ('owner', 'creator', 'cotizar.cotizacion.ver'),
  ('owner', 'creator', 'cotizar.cotizacion.crear'),
  ('owner', 'creator', 'cotizar.cotizacion.editar'),
  ('owner', 'creator', 'cotizar.cotizacion.enviar'),
  ('owner', 'creator', 'campanas.campana.ver'),
  ('owner', 'creator', 'campanas.campana.crear'),
  ('owner', 'creator', 'campanas.campana.editar'),
  ('owner', 'creator', 'campanas.post.asociar'),
  ('owner', 'creator', 'campanas.aporte.registrar'),
  ('owner', 'creator', 'campanas.resultado.calcular'),
  ('owner', 'creator', 'campanas.reporte.generar'),
  ('owner', 'creator', 'campanas.reporte.enviar'),
  ('owner', 'creator', 'finanzas.factura.ver'),
  ('owner', 'creator', 'finanzas.factura.crear'),
  ('owner', 'creator', 'finanzas.factura.editar'),
  ('owner', 'creator', 'finanzas.pago.registrar'),
  ('owner', 'creator', 'finanzas.cobro.ver'),
  ('owner', 'creator', 'finanzas.gasto.ver'),
  ('owner', 'creator', 'finanzas.gasto.registrar'),
  ('owner', 'creator', 'finanzas.flujo.ver'),
  ('owner', 'creator', 'finanzas.ajustes.configurar'),
  ('owner', 'creator', 'conexiones.cuenta.ver'),
  ('owner', 'creator', 'conexiones.cuenta.conectar'),
  ('owner', 'creator', 'conexiones.cuenta.desconectar'),
  ('owner', 'creator', 'equipo.miembro.ver'),
  ('owner', 'creator', 'equipo.miembro.invitar'),
  ('owner', 'creator', 'equipo.miembro.revocar'),
  ('owner', 'creator', 'equipo.rol.editar'),
  ('owner', 'creator', 'equipo.workspace.configurar'),
  ('manager', 'creator', 'resumen.panel.ver'),
  ('manager', 'creator', 'ventas.senal.ver'),
  ('manager', 'creator', 'ventas.senal.registrar'),
  ('manager', 'creator', 'ventas.senal.importar'),
  ('manager', 'creator', 'ventas.empresa.ver'),
  ('manager', 'creator', 'ventas.empresa.crear'),
  ('manager', 'creator', 'ventas.empresa.editar'),
  ('manager', 'creator', 'ventas.negocio.ver'),
  ('manager', 'creator', 'ventas.negocio.crear'),
  ('manager', 'creator', 'ventas.negocio.editar'),
  ('manager', 'creator', 'cotizar.tarifario.ver'),
  ('manager', 'creator', 'cotizar.tarifario.editar'),
  ('manager', 'creator', 'cotizar.mediakit.ver'),
  ('manager', 'creator', 'cotizar.mediakit.generar'),
  ('manager', 'creator', 'cotizar.mediakit.editar'),
  ('manager', 'creator', 'cotizar.cotizacion.ver'),
  ('manager', 'creator', 'cotizar.cotizacion.crear'),
  ('manager', 'creator', 'cotizar.cotizacion.editar'),
  ('manager', 'creator', 'cotizar.cotizacion.enviar'),
  ('manager', 'creator', 'campanas.campana.ver'),
  ('manager', 'creator', 'campanas.campana.crear'),
  ('manager', 'creator', 'campanas.campana.editar'),
  ('manager', 'creator', 'campanas.post.asociar'),
  ('manager', 'creator', 'campanas.aporte.registrar'),
  ('manager', 'creator', 'campanas.resultado.calcular'),
  ('manager', 'creator', 'campanas.reporte.generar'),
  ('manager', 'creator', 'campanas.reporte.enviar'),
  ('manager', 'creator', 'finanzas.cobro.ver'),
  ('manager', 'creator', 'conexiones.cuenta.ver'),
  ('manager', 'creator', 'equipo.miembro.ver'),
  ('editor', 'creator', 'resumen.panel.ver'),
  ('editor', 'creator', 'campanas.campana.ver'),
  ('editor', 'creator', 'campanas.post.asociar'),
  ('editor', 'creator', 'conexiones.cuenta.ver'),
  ('finance', 'creator', 'finanzas.factura.ver'),
  ('finance', 'creator', 'finanzas.factura.crear'),
  ('finance', 'creator', 'finanzas.factura.editar'),
  ('finance', 'creator', 'finanzas.pago.registrar'),
  ('finance', 'creator', 'finanzas.cobro.ver'),
  ('finance', 'creator', 'finanzas.gasto.ver'),
  ('finance', 'creator', 'finanzas.gasto.registrar'),
  ('finance', 'creator', 'finanzas.flujo.ver'),
  ('finance', 'creator', 'finanzas.ajustes.configurar'),
  ('viewer', 'creator', 'resumen.panel.ver'),
  ('viewer', 'creator', 'ventas.senal.ver'),
  ('viewer', 'creator', 'ventas.empresa.ver'),
  ('viewer', 'creator', 'ventas.negocio.ver'),
  ('viewer', 'creator', 'cotizar.tarifario.ver'),
  ('viewer', 'creator', 'cotizar.mediakit.ver'),
  ('viewer', 'creator', 'cotizar.cotizacion.ver'),
  ('viewer', 'creator', 'campanas.campana.ver'),
  ('viewer', 'creator', 'conexiones.cuenta.ver'),
  ('owner', 'agency', 'resumen.panel.ver'),
  ('owner', 'agency', 'resumen.metricas.importar'),
  ('owner', 'agency', 'ventas.senal.ver'),
  ('owner', 'agency', 'ventas.senal.registrar'),
  ('owner', 'agency', 'ventas.senal.importar'),
  ('owner', 'agency', 'ventas.empresa.ver'),
  ('owner', 'agency', 'ventas.empresa.crear'),
  ('owner', 'agency', 'ventas.empresa.editar'),
  ('owner', 'agency', 'ventas.negocio.ver'),
  ('owner', 'agency', 'ventas.negocio.crear'),
  ('owner', 'agency', 'ventas.negocio.editar'),
  ('owner', 'agency', 'cotizar.tarifario.ver'),
  ('owner', 'agency', 'cotizar.tarifario.editar'),
  ('owner', 'agency', 'cotizar.mediakit.ver'),
  ('owner', 'agency', 'cotizar.mediakit.generar'),
  ('owner', 'agency', 'cotizar.mediakit.editar'),
  ('owner', 'agency', 'cotizar.cotizacion.ver'),
  ('owner', 'agency', 'cotizar.cotizacion.crear'),
  ('owner', 'agency', 'cotizar.cotizacion.editar'),
  ('owner', 'agency', 'cotizar.cotizacion.enviar'),
  ('owner', 'agency', 'campanas.campana.ver'),
  ('owner', 'agency', 'campanas.campana.crear'),
  ('owner', 'agency', 'campanas.campana.editar'),
  ('owner', 'agency', 'campanas.post.asociar'),
  ('owner', 'agency', 'campanas.aporte.registrar'),
  ('owner', 'agency', 'campanas.resultado.calcular'),
  ('owner', 'agency', 'campanas.reporte.generar'),
  ('owner', 'agency', 'campanas.reporte.enviar'),
  ('owner', 'agency', 'finanzas.factura.ver'),
  ('owner', 'agency', 'finanzas.factura.crear'),
  ('owner', 'agency', 'finanzas.factura.editar'),
  ('owner', 'agency', 'finanzas.pago.registrar'),
  ('owner', 'agency', 'finanzas.cobro.ver'),
  ('owner', 'agency', 'finanzas.gasto.ver'),
  ('owner', 'agency', 'finanzas.gasto.registrar'),
  ('owner', 'agency', 'finanzas.flujo.ver'),
  ('owner', 'agency', 'finanzas.ajustes.configurar'),
  ('owner', 'agency', 'conexiones.cuenta.ver'),
  ('owner', 'agency', 'conexiones.cuenta.conectar'),
  ('owner', 'agency', 'conexiones.cuenta.desconectar'),
  ('owner', 'agency', 'equipo.miembro.ver'),
  ('owner', 'agency', 'equipo.miembro.invitar'),
  ('owner', 'agency', 'equipo.miembro.revocar'),
  ('owner', 'agency', 'equipo.rol.editar'),
  ('owner', 'agency', 'equipo.workspace.configurar'),
  ('admin', 'agency', 'resumen.panel.ver'),
  ('admin', 'agency', 'resumen.metricas.importar'),
  ('admin', 'agency', 'ventas.senal.ver'),
  ('admin', 'agency', 'ventas.senal.registrar'),
  ('admin', 'agency', 'ventas.senal.importar'),
  ('admin', 'agency', 'ventas.empresa.ver'),
  ('admin', 'agency', 'ventas.empresa.crear'),
  ('admin', 'agency', 'ventas.empresa.editar'),
  ('admin', 'agency', 'ventas.negocio.ver'),
  ('admin', 'agency', 'ventas.negocio.crear'),
  ('admin', 'agency', 'ventas.negocio.editar'),
  ('admin', 'agency', 'cotizar.tarifario.ver'),
  ('admin', 'agency', 'cotizar.tarifario.editar'),
  ('admin', 'agency', 'cotizar.mediakit.ver'),
  ('admin', 'agency', 'cotizar.mediakit.generar'),
  ('admin', 'agency', 'cotizar.mediakit.editar'),
  ('admin', 'agency', 'cotizar.cotizacion.ver'),
  ('admin', 'agency', 'cotizar.cotizacion.crear'),
  ('admin', 'agency', 'cotizar.cotizacion.editar'),
  ('admin', 'agency', 'cotizar.cotizacion.enviar'),
  ('admin', 'agency', 'campanas.campana.ver'),
  ('admin', 'agency', 'campanas.campana.crear'),
  ('admin', 'agency', 'campanas.campana.editar'),
  ('admin', 'agency', 'campanas.post.asociar'),
  ('admin', 'agency', 'campanas.aporte.registrar'),
  ('admin', 'agency', 'campanas.resultado.calcular'),
  ('admin', 'agency', 'campanas.reporte.generar'),
  ('admin', 'agency', 'campanas.reporte.enviar'),
  ('admin', 'agency', 'finanzas.factura.ver'),
  ('admin', 'agency', 'finanzas.factura.crear'),
  ('admin', 'agency', 'finanzas.factura.editar'),
  ('admin', 'agency', 'finanzas.pago.registrar'),
  ('admin', 'agency', 'finanzas.cobro.ver'),
  ('admin', 'agency', 'finanzas.gasto.ver'),
  ('admin', 'agency', 'finanzas.gasto.registrar'),
  ('admin', 'agency', 'finanzas.flujo.ver'),
  ('admin', 'agency', 'finanzas.ajustes.configurar'),
  ('admin', 'agency', 'conexiones.cuenta.ver'),
  ('admin', 'agency', 'conexiones.cuenta.conectar'),
  ('admin', 'agency', 'conexiones.cuenta.desconectar'),
  ('admin', 'agency', 'equipo.miembro.ver'),
  ('admin', 'agency', 'equipo.miembro.invitar'),
  ('admin', 'agency', 'equipo.miembro.revocar'),
  ('admin', 'agency', 'equipo.rol.editar'),
  ('manager', 'agency', 'ventas.senal.ver'),
  ('manager', 'agency', 'ventas.senal.registrar'),
  ('manager', 'agency', 'ventas.senal.importar'),
  ('manager', 'agency', 'ventas.empresa.ver'),
  ('manager', 'agency', 'ventas.empresa.crear'),
  ('manager', 'agency', 'ventas.empresa.editar'),
  ('manager', 'agency', 'ventas.negocio.ver'),
  ('manager', 'agency', 'ventas.negocio.crear'),
  ('manager', 'agency', 'ventas.negocio.editar'),
  ('manager', 'agency', 'cotizar.tarifario.ver'),
  ('manager', 'agency', 'cotizar.tarifario.editar'),
  ('manager', 'agency', 'cotizar.mediakit.ver'),
  ('manager', 'agency', 'cotizar.mediakit.generar'),
  ('manager', 'agency', 'cotizar.mediakit.editar'),
  ('manager', 'agency', 'cotizar.cotizacion.ver'),
  ('manager', 'agency', 'cotizar.cotizacion.crear'),
  ('manager', 'agency', 'cotizar.cotizacion.editar'),
  ('manager', 'agency', 'cotizar.cotizacion.enviar'),
  ('manager', 'agency', 'campanas.campana.ver'),
  ('manager', 'agency', 'campanas.campana.crear'),
  ('manager', 'agency', 'campanas.campana.editar'),
  ('manager', 'agency', 'campanas.post.asociar'),
  ('manager', 'agency', 'campanas.aporte.registrar'),
  ('manager', 'agency', 'campanas.resultado.calcular'),
  ('manager', 'agency', 'campanas.reporte.generar'),
  ('manager', 'agency', 'campanas.reporte.enviar'),
  ('finance', 'agency', 'finanzas.factura.ver'),
  ('finance', 'agency', 'finanzas.factura.crear'),
  ('finance', 'agency', 'finanzas.factura.editar'),
  ('finance', 'agency', 'finanzas.pago.registrar'),
  ('finance', 'agency', 'finanzas.cobro.ver'),
  ('finance', 'agency', 'finanzas.gasto.ver'),
  ('finance', 'agency', 'finanzas.gasto.registrar'),
  ('finance', 'agency', 'finanzas.flujo.ver'),
  ('finance', 'agency', 'finanzas.ajustes.configurar'),
  ('viewer', 'agency', 'resumen.panel.ver'),
  ('viewer', 'agency', 'ventas.senal.ver'),
  ('viewer', 'agency', 'ventas.empresa.ver'),
  ('viewer', 'agency', 'ventas.negocio.ver'),
  ('viewer', 'agency', 'cotizar.tarifario.ver'),
  ('viewer', 'agency', 'cotizar.mediakit.ver'),
  ('viewer', 'agency', 'cotizar.cotizacion.ver'),
  ('viewer', 'agency', 'campanas.campana.ver'),
  ('viewer', 'agency', 'conexiones.cuenta.ver')
) AS m (role_key, workspace_kind, permission_key)
JOIN role r ON r.key = m.role_key AND r.workspace_kind = m.workspace_kind AND r.workspace_id IS NULL
ON CONFLICT DO NOTHING;
